// Datos de configuracion del tablero: temas, iconos preestablecidos, bancos
// chilenos y categorias. Estaban en App.jsx, donde ocupaban 478 de sus 3733
// lineas sin ser logica de ningun componente.

import {
  Apple,
  Baby,
  Beer,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Calculator,
  Candy,
  Car,
  ClipboardList,
  Cloud,
  Coffee,
  Coins,
  DollarSign,
  Droplets,
  Dumbbell,
  Film,
  Flame,
  Fuel,
  Gamepad2,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  Headphones,
  Heart,
  Home,
  Key,
  Landmark,
  Laptop,
  LayoutDashboard,
  Lock,
  Mail,
  Monitor,
  Music,
  Package,
  Palette,
  ParkingCircle,
  Percent,
  Phone,
  Pizza,
  Plane,
  Printer,
  Radio,
  Receipt,
  RefreshCw,
  Salad,
  Scissors,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Star,
  Stethoscope,
  Store,
  Train,
  Truck,
  Tv,
  Utensils,
  Wifi,
  Zap,
  CreditCard as CreditCardIcon,
} from 'lucide-react';

export const apiKey = import.meta.env.VITE_GEMINI_API_KEY;

// Claves que viajan a /api/sync. Se comparan una a una para enviar solo las
// que cambiaron desde el ultimo guardado confirmado.
export const CLAVES_SINCRONIZADAS = ['months', 'deudas', 'gastosFijos', 'abonos', 'sueldos', 'cuentasAhorro', 'ahorrosData', 'suscripciones'];

export const MONTH_NAMES = [
  'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
  'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'
];

export const INITIAL_MONTHS = [
  'Enero 2026', 'Febrero 2026', 'Marzo 2026', 'Abril 2026', 'Mayo 2026', 'Junio 2026',
  'Julio 2026', 'Agosto 2026', 'Septiembre 2026', 'Octubre 2026', 'Noviembre 2026', 'Diciembre 2026'
];

export const THEMES = {
  // El tema de marca. Antes eran clases emerald de Tailwind (#10B981), no el
  // Mint Green de brand.md (#2DBC8B): el color corporativo no aparecia en
  // ninguna parte de la aplicacion.
  kk: {
    btnPrimary: 'bg-kk-primary hover:bg-kk-dark text-white',
    shadowBtn: 'shadow-kk-light dark:shadow-kk-dark/30',
    focusBorder: 'focus:border-kk-primary',
    hoverBorder: 'hover:border-kk-secondary',
    iconAccent: 'text-kk-primary',
    iconAccentDark: 'dark:text-kk-secondary',
    bgLight: 'bg-kk-light/50',
    bgLightDark: 'dark:bg-kk-dark/20',
    bgLightSolid: 'bg-kk-light',
    bgLightDarkSolid: 'dark:bg-kk-dark',
    badgeBg: 'bg-kk-light',
    badgeBgDark: 'dark:bg-kk-dark/30',
    badgeText: 'text-kk-dark',
    badgeTextDark: 'dark:text-kk-secondary',
    tabText: 'text-kk-dark',
    headerIcon: 'bg-kk-primary',
    headerIconShadow: 'shadow-kk-light dark:shadow-kk-dark/30',
    btnDebt: 'bg-blue-600 hover:bg-blue-700 text-white',
    btnFixed: 'bg-sky-500 hover:bg-sky-600 text-white',
    btnSub: 'bg-rose-600 hover:bg-rose-700 text-white',
    modalPrimary: 'bg-kk-primary hover:bg-kk-dark text-white',
    borderAccent: 'border-kk-primary',
    bgModalLight: 'bg-kk-light dark:bg-kk-dark/30',
    inputBg: 'bg-kk-light/50 dark:bg-kk-dark/20',
  },
  indigo: {
    btnPrimary: 'bg-indigo-600 hover:bg-indigo-700',
    shadowBtn: 'shadow-indigo-100 dark:shadow-indigo-900/30',
    focusBorder: 'focus:border-indigo-500',
    hoverBorder: 'hover:border-indigo-300',
    iconAccent: 'text-indigo-400',
    iconAccentDark: 'dark:text-indigo-300',
    bgLight: 'bg-indigo-50/50',
    bgLightDark: 'dark:bg-indigo-900/20',
    bgLightSolid: 'bg-indigo-50',
    bgLightDarkSolid: 'dark:bg-indigo-900',
    badgeBg: 'bg-indigo-100',
    badgeBgDark: 'dark:bg-indigo-900/30',
    badgeText: 'text-indigo-700',
    badgeTextDark: 'dark:text-indigo-300',
    tabText: 'text-indigo-600',
    headerIcon: 'bg-indigo-600',
    headerIconShadow: 'shadow-indigo-200 dark:shadow-indigo-900/30',
    btnDebt: 'bg-indigo-600 hover:bg-indigo-700',
    btnFixed: 'bg-slate-800 dark:bg-dark-lighter hover:bg-slate-900 dark:hover:bg-dark-lightest',
    btnSub: 'bg-rose-600 hover:bg-rose-700',
    modalPrimary: 'bg-indigo-600 hover:bg-indigo-700',
    borderAccent: 'border-indigo-600',
    bgModalLight: 'bg-indigo-50 dark:bg-indigo-900/30',
    inputBg: 'bg-indigo-50/50 dark:bg-indigo-900/20',
  },
  blue: {
    btnPrimary: 'bg-blue-600 hover:bg-blue-700',
    shadowBtn: 'shadow-blue-100 dark:shadow-blue-900/30',
    focusBorder: 'focus:border-blue-500',
    hoverBorder: 'hover:border-blue-300',
    iconAccent: 'text-blue-400',
    iconAccentDark: 'dark:text-blue-300',
    bgLight: 'bg-blue-50/50',
    bgLightDark: 'dark:bg-blue-900/20',
    bgLightSolid: 'bg-blue-50',
    bgLightDarkSolid: 'dark:bg-blue-900',
    badgeBg: 'bg-blue-100',
    badgeBgDark: 'dark:bg-blue-900/30',
    badgeText: 'text-blue-700',
    badgeTextDark: 'dark:text-blue-300',
    tabText: 'text-blue-600',
    headerIcon: 'bg-blue-600',
    headerIconShadow: 'shadow-blue-200 dark:shadow-blue-900/30',
    btnDebt: 'bg-blue-600 hover:bg-blue-700',
    btnFixed: 'bg-slate-800 dark:bg-dark-lighter hover:bg-slate-900 dark:hover:bg-dark-lightest',
    btnSub: 'bg-rose-600 hover:bg-rose-700',
    modalPrimary: 'bg-blue-600 hover:bg-blue-700',
    borderAccent: 'border-blue-600',
    bgModalLight: 'bg-blue-50 dark:bg-blue-900/30',
    inputBg: 'bg-blue-50/50 dark:bg-blue-900/20',
  },
  emerald: {
    btnPrimary: 'bg-emerald-600 hover:bg-emerald-700',
    shadowBtn: 'shadow-emerald-100 dark:shadow-emerald-900/30',
    focusBorder: 'focus:border-emerald-500',
    hoverBorder: 'hover:border-emerald-300',
    iconAccent: 'text-emerald-400',
    iconAccentDark: 'dark:text-emerald-300',
    bgLight: 'bg-emerald-50/50',
    bgLightDark: 'dark:bg-emerald-900/20',
    bgLightSolid: 'bg-emerald-50',
    bgLightDarkSolid: 'dark:bg-emerald-900',
    badgeBg: 'bg-emerald-100',
    badgeBgDark: 'dark:bg-emerald-900/30',
    badgeText: 'text-emerald-700',
    badgeTextDark: 'dark:text-emerald-300',
    tabText: 'text-emerald-600',
    headerIcon: 'bg-emerald-600',
    headerIconShadow: 'shadow-emerald-200 dark:shadow-emerald-900/30',
    btnDebt: 'bg-emerald-600 hover:bg-emerald-700',
    btnFixed: 'bg-slate-800 dark:bg-dark-lighter hover:bg-slate-900 dark:hover:bg-dark-lightest',
    btnSub: 'bg-rose-600 hover:bg-rose-700',
    modalPrimary: 'bg-emerald-600 hover:bg-emerald-700',
    borderAccent: 'border-emerald-600',
    bgModalLight: 'bg-emerald-50 dark:bg-emerald-900/30',
    inputBg: 'bg-emerald-50/50 dark:bg-emerald-900/20',
  },
  purple: {
    btnPrimary: 'bg-purple-600 hover:bg-purple-700',
    shadowBtn: 'shadow-purple-100 dark:shadow-purple-900/30',
    focusBorder: 'focus:border-purple-500',
    hoverBorder: 'hover:border-purple-300',
    iconAccent: 'text-purple-400',
    iconAccentDark: 'dark:text-purple-300',
    bgLight: 'bg-purple-50/50',
    bgLightDark: 'dark:bg-purple-900/20',
    bgLightSolid: 'bg-purple-50',
    bgLightDarkSolid: 'dark:bg-purple-900',
    badgeBg: 'bg-purple-100',
    badgeBgDark: 'dark:bg-purple-900/30',
    badgeText: 'text-purple-700',
    badgeTextDark: 'dark:text-purple-300',
    tabText: 'text-purple-600',
    headerIcon: 'bg-purple-600',
    headerIconShadow: 'shadow-purple-200 dark:shadow-purple-900/30',
    btnDebt: 'bg-purple-600 hover:bg-purple-700',
    btnFixed: 'bg-slate-800 dark:bg-dark-lighter hover:bg-slate-900 dark:hover:bg-dark-lightest',
    btnSub: 'bg-rose-600 hover:bg-rose-700',
    modalPrimary: 'bg-purple-600 hover:bg-purple-700',
    borderAccent: 'border-purple-600',
    bgModalLight: 'bg-purple-50 dark:bg-purple-900/30',
    inputBg: 'bg-purple-50/50 dark:bg-purple-900/20',
  },
  rose: {
    btnPrimary: 'bg-rose-600 hover:bg-rose-700',
    shadowBtn: 'shadow-rose-100 dark:shadow-rose-900/30',
    focusBorder: 'focus:border-rose-500',
    hoverBorder: 'hover:border-rose-300',
    iconAccent: 'text-rose-400',
    iconAccentDark: 'dark:text-rose-300',
    bgLight: 'bg-rose-50/50',
    bgLightDark: 'dark:bg-rose-900/20',
    bgLightSolid: 'bg-rose-50',
    bgLightDarkSolid: 'dark:bg-rose-900',
    badgeBg: 'bg-rose-100',
    badgeBgDark: 'dark:bg-rose-900/30',
    badgeText: 'text-rose-700',
    badgeTextDark: 'dark:text-rose-300',
    tabText: 'text-rose-600',
    headerIcon: 'bg-rose-600',
    headerIconShadow: 'shadow-rose-200 dark:shadow-rose-900/30',
    btnDebt: 'bg-rose-600 hover:bg-rose-700',
    btnFixed: 'bg-slate-800 dark:bg-dark-lighter hover:bg-slate-900 dark:hover:bg-dark-lightest',
    btnSub: 'bg-rose-600 hover:bg-rose-700',
    modalPrimary: 'bg-rose-600 hover:bg-rose-700',
    borderAccent: 'border-rose-600',
    bgModalLight: 'bg-rose-50 dark:bg-rose-900/30',
    inputBg: 'bg-rose-50/50 dark:bg-rose-900/20',
  },
  amber: {
    btnPrimary: 'bg-amber-600 hover:bg-amber-700',
    shadowBtn: 'shadow-amber-100 dark:shadow-amber-900/30',
    focusBorder: 'focus:border-amber-500',
    hoverBorder: 'hover:border-amber-300',
    iconAccent: 'text-amber-400',
    iconAccentDark: 'dark:text-amber-300',
    bgLight: 'bg-amber-50/50',
    bgLightDark: 'dark:bg-amber-900/20',
    bgLightSolid: 'bg-amber-50',
    bgLightDarkSolid: 'dark:bg-amber-900',
    badgeBg: 'bg-amber-100',
    badgeBgDark: 'dark:bg-amber-900/30',
    badgeText: 'text-amber-700',
    badgeTextDark: 'dark:text-amber-300',
    tabText: 'text-amber-600',
    headerIcon: 'bg-amber-600',
    headerIconShadow: 'shadow-amber-200 dark:shadow-amber-900/30',
    btnDebt: 'bg-amber-600 hover:bg-amber-700',
    btnFixed: 'bg-slate-800 dark:bg-dark-lighter hover:bg-slate-900 dark:hover:bg-dark-lightest',
    btnSub: 'bg-rose-600 hover:bg-rose-700',
    modalPrimary: 'bg-amber-600 hover:bg-amber-700',
    borderAccent: 'border-amber-600',
    bgModalLight: 'bg-amber-50 dark:bg-amber-900/30',
    inputBg: 'bg-amber-50/50 dark:bg-amber-900/20',
  },
  teal: {
    btnPrimary: 'bg-teal-600 hover:bg-teal-700',
    shadowBtn: 'shadow-teal-100 dark:shadow-teal-900/30',
    focusBorder: 'focus:border-teal-500',
    hoverBorder: 'hover:border-teal-300',
    iconAccent: 'text-teal-400',
    iconAccentDark: 'dark:text-teal-300',
    bgLight: 'bg-teal-50/50',
    bgLightDark: 'dark:bg-teal-900/20',
    bgLightSolid: 'bg-teal-50',
    bgLightDarkSolid: 'dark:bg-teal-900',
    badgeBg: 'bg-teal-100',
    badgeBgDark: 'dark:bg-teal-900/30',
    badgeText: 'text-teal-700',
    badgeTextDark: 'dark:text-teal-300',
    tabText: 'text-teal-600',
    headerIcon: 'bg-teal-600',
    headerIconShadow: 'shadow-teal-200 dark:shadow-teal-900/30',
    btnDebt: 'bg-teal-600 hover:bg-teal-700',
    btnFixed: 'bg-slate-800 dark:bg-dark-lighter hover:bg-slate-900 dark:hover:bg-dark-lightest',
    btnSub: 'bg-rose-600 hover:bg-rose-700',
    modalPrimary: 'bg-teal-600 hover:bg-teal-700',
    borderAccent: 'border-teal-600',
    bgModalLight: 'bg-teal-50 dark:bg-teal-900/30',
    inputBg: 'bg-teal-50/50 dark:bg-teal-900/20',
  },
  slate: {
    btnPrimary: 'bg-slate-600 hover:bg-slate-700',
    shadowBtn: 'shadow-slate-100 dark:shadow-dark-darker/30',
    focusBorder: 'focus:border-slate-500',
    hoverBorder: 'hover:border-slate-300',
    iconAccent: 'text-slate-400',
    iconAccentDark: 'dark:text-slate-300',
    bgLight: 'bg-slate-50/50',
    bgLightDark: 'dark:bg-dark-darker/20',
    bgLightSolid: 'bg-slate-50',
    bgLightDarkSolid: 'dark:bg-dark-darker',
    badgeBg: 'bg-slate-100',
    badgeBgDark: 'dark:bg-dark-darker/30',
    badgeText: 'text-slate-700',
    badgeTextDark: 'dark:text-slate-300',
    tabText: 'text-slate-600',
    headerIcon: 'bg-slate-600',
    headerIconShadow: 'shadow-slate-200 dark:shadow-dark-darker/30',
    btnDebt: 'bg-slate-600 hover:bg-slate-700',
    btnFixed: 'bg-slate-800 dark:bg-dark-lighter hover:bg-slate-900 dark:hover:bg-dark-lightest',
    btnSub: 'bg-rose-600 hover:bg-rose-700',
    modalPrimary: 'bg-slate-600 hover:bg-slate-700',
    borderAccent: 'border-slate-600',
    bgModalLight: 'bg-slate-50 dark:bg-dark-darker/30',
    inputBg: 'bg-slate-50/50 dark:bg-dark-darker/20',
  },
};

export const THEME_COLOR_HEX = {
  kk: '#2DBC8B',
  indigo: '#4f46e5',
  blue: '#2563eb',
  emerald: '#059669',
  purple: '#9333ea',
  rose: '#e11d48',
  amber: '#d97706',
  teal: '#0d9488',
  slate: '#475569',
};

export const PRESET_ICONS = [
  { id: 'zap', icon: Zap, label: 'Luz', keywords: 'luz electricidad energia luz' },
  { id: 'droplets', icon: Droplets, label: 'Agua', keywords: 'agua gas agua' },
  { id: 'wifi', icon: Wifi, label: 'Internet', keywords: 'internet wifi red conexion' },
  { id: 'receipt', icon: Receipt, label: 'Gastos', keywords: 'gastos recibo factura' },
  { id: 'building', icon: Building2, label: 'GC', keywords: 'gastos comunes edificio condominio gc' },
  { id: 'layout', icon: LayoutDashboard, label: 'Otro', keywords: 'otro general varios' },
  { id: 'car', icon: Car, label: 'Auto', keywords: 'auto auto vehiculo transporte' },
  { id: 'phone', icon: Phone, label: 'Telefono', keywords: 'telefono celular movil' },
  { id: 'shield', icon: Shield, label: 'Seguro', keywords: 'seguro seguro proteccion' },
  { id: 'heart', icon: Heart, label: 'Salud', keywords: 'salud medico doctor salud' },
  { id: 'graduation-cap', icon: GraduationCap, label: 'Educacion', keywords: 'educacion estudio colegio universidad' },
  { id: 'shopping-bag', icon: ShoppingBag, label: 'Compras', keywords: 'compras tienda compras ropa' },
  { id: 'shopping-cart', icon: ShoppingCart, label: 'Supermercado', keywords: 'supermercado compras mercado' },
  { id: 'utensils', icon: Utensils, label: 'Restaurante', keywords: 'restaurante comida comer restaurante' },
  { id: 'coffee', icon: Coffee, label: 'Cafe', keywords: 'cafe desayuno cafe' },
  { id: 'home', icon: Home, label: 'Casa', keywords: 'casa hogar vivienda arriendo' },
  { id: 'monitor', icon: Monitor, label: 'Computador', keywords: 'computador pc monitor tecnologia' },
  { id: 'smartphone', icon: Smartphone, label: 'Celular', keywords: 'celular smartphone telefono' },
  { id: 'tv', icon: Tv, label: 'TV Cable', keywords: 'tv television cable streaming' },
  { id: 'gamepad-2', icon: Gamepad2, label: 'Gaming', keywords: 'gaming juegos entretenimiento' },
  { id: 'plane', icon: Plane, label: 'Viaje', keywords: 'viaje viaje vacaciones vuelo' },
  { id: 'dumbbell', icon: Dumbbell, label: 'Gym', keywords: 'gym ejercicio deporte gimnasio' },
  { id: 'stethoscope', icon: Stethoscope, label: 'Medico', keywords: 'medico doctor salud hospital' },
  { id: 'baby', icon: Baby, label: 'Bebe', keywords: 'bebe hijo nino guagua' },
  { id: 'gift', icon: Gift, label: 'Regalos', keywords: 'regalos regalo cumpleaños' },
  { id: 'scissors', icon: Scissors, label: 'Peluqueria', keywords: 'peluqueria corte pelo' },
  { id: 'fuel', icon: Fuel, label: 'Combustible', keywords: 'combustible bencina gasolina' },
  { id: 'parking-circle', icon: ParkingCircle, label: 'Estacionamiento', keywords: 'estacionamiento parking estacionar' },
  { id: 'bus', icon: Bus, label: 'Transporte', keywords: 'transporte bus micro transporte publico' },
  { id: 'train', icon: Train, label: 'Tren', keywords: 'tren metro ferrocarril' },
  { id: 'landmark', icon: Landmark, label: 'Banco', keywords: 'banco banco credito financiera' },
  { id: 'credit-card', icon: CreditCardIcon, label: 'Tarjeta', keywords: 'tarjeta credito debito' },
  { id: 'dollar-sign', icon: DollarSign, label: 'Dinero', keywords: 'dinero plata dinero' },
  { id: 'coins', icon: Coins, label: 'Monedas', keywords: 'monedas ahorro monedas' },
  { id: 'percent', icon: Percent, label: 'Impuestos', keywords: 'impuestos tasa interes porcentaje' },
  { id: 'calculator', icon: Calculator, label: 'Contabilidad', keywords: 'contabilidad calcular calculo' },
  { id: 'clipboard-list', icon: ClipboardList, label: 'Lista', keywords: 'lista tareas pendientes' },
  { id: 'book-open', icon: BookOpen, label: 'Libro', keywords: 'libro lectura curso libro' },
  { id: 'laptop', icon: Laptop, label: 'Notebook', keywords: 'notebook laptop computador portatil' },
  { id: 'printer', icon: Printer, label: 'Impresora', keywords: 'impresora imprimir' },
  { id: 'key', icon: Key, label: 'Llave', keywords: 'llave acceso' },
  { id: 'lock', icon: Lock, label: 'Candado', keywords: 'candado seguridad' },
  { id: 'mail', icon: Mail, label: 'Correo', keywords: 'correo email' },
  { id: 'package', icon: Package, label: 'Paquete', keywords: 'paquete envio delivery' },
  { id: 'truck', icon: Truck, label: 'Despacho', keywords: 'despacho envio camion' },
  { id: 'store', icon: Store, label: 'Tienda', keywords: 'tienda negocio comercio' },
  { id: 'music', icon: Music, label: 'Musica', keywords: 'musica spotify audio' },
  { id: 'film', icon: Film, label: 'Pelicula', keywords: 'pelicula netflix video cine' },
  { id: 'palette', icon: Palette, label: 'Arte', keywords: 'arte pintura disenio' },
  { id: 'briefcase', icon: Briefcase, label: 'Trabajo', keywords: 'trabajo oficina empleo' },
  { id: 'hammer', icon: Hammer, label: 'Herramienta', keywords: 'herramienta reparacion construccion' },
  { id: 'flame', icon: Flame, label: 'Gas', keywords: 'gas calefaccion fuego' },
  { id: 'pizza', icon: Pizza, label: 'Pizza', keywords: 'pizza comida rapida' },
  { id: 'candy', icon: Candy, label: 'Dulces', keywords: 'dulces snacks golosinas' },
  { id: 'beer', icon: Beer, label: 'Cerveza', keywords: 'cerveza bar bebida alcohol' },
   { id: 'salad', icon: Salad, label: 'Verduras', keywords: 'verduras saludable ensalada' }
];

export const BANCOS_CHILE = [
  { id: 'banco-de-chile', nombre: 'Banco de Chile', logo: '/bancos/banco-de-chile.png', tipos: ['visa', 'mastercard'] },
  { id: 'banco-santander', nombre: 'Banco Santander', logo: '/bancos/banco-santander.png', tipos: ['visa', 'mastercard'] },
  { id: 'banco-estado', nombre: 'BancoEstado', logo: '/bancos/banco-estado.png', tipos: ['visa', 'mastercard'] },
  { id: 'banco-de-credito', nombre: 'Banco de Crédito e Inversiones (BCI)', logo: '/bancos/banco-de-credito.png', tipos: ['visa', 'mastercard'] },
  { id: 'banco-scotiabank', nombre: 'Scotiabank Chile', logo: '/bancos/banco-scotiabank.png', tipos: ['visa', 'mastercard'] },
  { id: 'banco-itau', nombre: 'Itaú Corpbanca', logo: '/bancos/banco-itau.png', tipos: ['visa', 'mastercard'] },
  { id: 'banco-falabella', nombre: 'Banco Falabella', logo: '/bancos/banco-falabella.png', tipos: ['visa', 'mastercard'] },
  { id: 'banco-ripley', nombre: 'Banco Ripley', logo: '/bancos/banco-ripley.png', tipos: ['visa', 'mastercard'] },
  { id: 'banco-paris', nombre: 'Banco Paris', logo: '/bancos/banco-paris.png', tipos: ['visa', 'mastercard'] },
  { id: 'banco-cencosud', nombre: 'Banco Cencosud', logo: '/bancos/banco-cencosud.png', tipos: ['visa', 'mastercard'] },
  { id: 'banco-security', nombre: 'Banco Security', logo: '/bancos/banco-security.png', tipos: ['visa', 'mastercard'] },
  { id: 'banco-rabobank', nombre: 'Rabobank Chile', logo: '/bancos/banco-rabobank.png', tipos: ['visa', 'mastercard'] },
  { id: 'banco-internacional', nombre: 'Banco Internacional', logo: '/bancos/banco-internacional.png', tipos: ['visa', 'mastercard'] },
  { id: 'banco-bice', nombre: 'Banco BICE', logo: '/bancos/banco-bice.png', tipos: ['visa', 'mastercard'] },
  { id: 'banco-hsbc', nombre: 'HSBC Bank Chile', logo: '/bancos/banco-hsbc.png', tipos: ['visa', 'mastercard'] },
  { id: 'coopeuch', nombre: 'Coopeuch', logo: '/bancos/coopeuch.png', tipos: ['visa', 'mastercard'] },
  { id: 'banco-consorcio', nombre: 'Banco Consorcio', logo: '/bancos/banco-consorcio.png', tipos: ['visa', 'mastercard'] },
  { id: 'tenpo', nombre: 'Tenpo', logo: '/bancos/tenpo.png', tipos: ['visa', 'mastercard'] },
  { id: 'mach', nombre: 'Mach', logo: '/bancos/mach.png', tipos: ['visa', 'mastercard'] },
  { id: 'lider', nombre: 'Banco Líder', logo: '/bancos/lider.png', tipos: ['visa', 'mastercard'] },
  { id: 'mercadopago', nombre: 'Mercado Pago', logo: '/bancos/mercadopago.png', tipos: ['visa', 'mastercard'] }
];

export const SUBSCRIPTION_ICONS = [
  { id: 'film', icon: Film, label: 'Netflix', keywords: 'netflix cine peliculas streaming video' },
  { id: 'tv', icon: Tv, label: 'TV Cable', keywords: 'tv cable television' },
  { id: 'monitor', icon: Monitor, label: 'YouTube', keywords: 'youtube video google' },
  { id: 'music', icon: Music, label: 'Spotify', keywords: 'spotify musica audio streaming' },
  { id: 'headphones', icon: Headphones, label: 'Apple Music', keywords: 'apple music musica audio streaming' },
  { id: 'gamepad-2', icon: Gamepad2, label: 'Twitch', keywords: 'twitch gaming streaming juegos' },
  { id: 'star', icon: Star, label: 'Disney+', keywords: 'disney plus streaming peliculas' },
  { id: 'globe', icon: Globe, label: 'HBO Max', keywords: 'hbo max streaming peliculas series' },
  { id: 'refresh-cw', icon: RefreshCw, label: 'Amazon Prime', keywords: 'amazon prime video compras' },
  { id: 'radio', icon: Radio, label: 'Podcast', keywords: 'podcast radio audio' },
  { id: 'zap', icon: Zap, label: 'Luz', keywords: 'luz electricidad energia' },
  { id: 'droplets', icon: Droplets, label: 'Agua', keywords: 'agua gas' },
  { id: 'wifi', icon: Wifi, label: 'Internet', keywords: 'internet wifi red conexion' },
  { id: 'smartphone', icon: Smartphone, label: 'Celular', keywords: 'celular smartphone telefono' },
  { id: 'shield', icon: Shield, label: 'Seguro', keywords: 'seguro seguro proteccion' },
  { id: 'heart', icon: Heart, label: 'Salud', keywords: 'salud medico doctor' },
  { id: 'dumbbell', icon: Dumbbell, label: 'Gym', keywords: 'gym ejercicio deporte' },
  { id: 'cloud', icon: Cloud, label: 'Cloud', keywords: 'cloud almacenamiento nube icloud google drive' },
  { id: 'layout', icon: LayoutDashboard, label: 'Otro', keywords: 'otro general varios' }
];

export const CHILE_PRESET_ICONS = {
  bancos: [
    { id: 'banco_bice', label: 'Banco BICE', path: '/chile-icons/bancos/banco_bice.png', keywords: 'bice banco' },
    { id: 'banco_de_chile', label: 'Banco de Chile', path: '/chile-icons/bancos/banco_de_chile.png', keywords: 'banco chile' },
    { id: 'banco_do_brasil', label: 'Banco do Brasil', path: '/chile-icons/bancos/banco_do_brasil.png', keywords: 'brasil banco' },
    { id: 'banco_estado', label: 'BancoEstado', path: '/chile-icons/bancos/banco_estado.png', keywords: 'estado banco' },
    { id: 'banco_falabella', label: 'Banco Falabella', path: '/chile-icons/bancos/banco_falabella.png', keywords: 'falabella banco' },
    { id: 'banco_internacional', label: 'Banco Internacional', path: '/chile-icons/bancos/banco_internacional.png', keywords: 'internacional banco' },
    { id: 'banco_ripley', label: 'Banco Ripley', path: '/chile-icons/bancos/banco_ripley.png', keywords: 'ripley banco' },
    { id: 'banco_security', label: 'Banco Security', path: '/chile-icons/bancos/banco_security.png', keywords: 'security banco' },
    { id: 'bbva', label: 'BBVA', path: '/chile-icons/bancos/bbva.png', keywords: 'bbva banco' },
    { id: 'bci', label: 'BCI', path: '/chile-icons/bancos/bci.png', keywords: 'bci banco credito inversiones' },
    { id: 'consorcio', label: 'Consorcio', path: '/chile-icons/bancos/consorcio.png', keywords: 'consorcio banco' },
    { id: 'coopeuch', label: 'Coopeuch', path: '/chile-icons/bancos/coopeuch.png', keywords: 'coopeuch banco' },
    { id: 'corpbanca', label: 'Corpbanca', path: '/chile-icons/bancos/corpbanca.png', keywords: 'corpbanca banco itau' },
    { id: 'hsbc', label: 'HSBC', path: '/chile-icons/bancos/hsbc.png', keywords: 'hsbc banco' },
    { id: 'itau', label: 'Itaú', path: '/chile-icons/bancos/itau.png', keywords: 'itau banco corpbanca' },
    { id: 'paris', label: 'París', path: '/chile-icons/bancos/paris.png', keywords: 'paris banco' },
    { id: 'prepago_los_heroes', label: 'Prepago Los Héroes', path: '/chile-icons/bancos/prepago_los_heroes.png', keywords: 'prepago heroes heroes' },
    { id: 'santander', label: 'Santander', path: '/chile-icons/bancos/santander.png', keywords: 'santander banco' },
    { id: 'scotiabank', label: 'Scotiabank', path: '/chile-icons/bancos/scotiabank.png', keywords: 'scotiabank banco' },
    { id: 'mercadopago', label: 'Mercado Pago', path: '/chile-icons/medios-pago/mercadopago.png', keywords: 'mercadopago banco pago' },
  ],
  isapres: [
    { id: 'banmedica', label: 'Banmédica', path: '/chile-icons/isapres/banmedica.png', keywords: 'banmedica isapre salud' },
    { id: 'colmena', label: 'Colmena', path: '/chile-icons/isapres/colmena.png', keywords: 'colmena isapre salud' },
    { id: 'consalud', label: 'Consalud', path: '/chile-icons/isapres/consalud.png', keywords: 'consalud isapre salud' },
    { id: 'cruz_blanca', label: 'Cruz Blanca', path: '/chile-icons/isapres/cruz_blanca.png', keywords: 'cruz blanca isapre salud' },
    { id: 'vidatres', label: 'Vida Tres', path: '/chile-icons/isapres/vidatres.png', keywords: 'vidatres vida tres isapre salud' },
  ],
  afp: [
    { id: 'capital', label: 'Capital', path: '/chile-icons/afp/capital.png', keywords: 'capital afp' },
    { id: 'cuprum', label: 'Cuprum', path: '/chile-icons/afp/cuprum.png', keywords: 'cuprum afp' },
    { id: 'habitat', label: 'Habitat', path: '/chile-icons/afp/habitat.png', keywords: 'habitat afp' },
    { id: 'modelo', label: 'Modelo', path: '/chile-icons/afp/modelo.png', keywords: 'modelo afp' },
    { id: 'plan_vital', label: 'PlanVital', path: '/chile-icons/afp/plan_vital.png', keywords: 'plan vital afp' },
    { id: 'provida', label: 'Provida', path: '/chile-icons/afp/provida.png', keywords: 'provida afp' },
    { id: 'sura', label: 'SURA', path: '/chile-icons/afp/sura.png', keywords: 'sura afp' },
  ],
  telefonia: [
    { id: 'claro', label: 'Claro', path: '/chile-icons/telefonia/claro.png', keywords: 'claro telefono celular' },
    { id: 'entel', label: 'Entel', path: '/chile-icons/telefonia/entel.png', keywords: 'entel telefono celular' },
    { id: 'movistar', label: 'Movistar', path: '/chile-icons/telefonia/movistar.png', keywords: 'movistar telefono celular' },
    { id: 'virgin', label: 'Virgin', path: '/chile-icons/telefonia/virgin.png', keywords: 'virgin telefono celular' },
    { id: 'wom', label: 'WOM', path: '/chile-icons/telefonia/wom.png', keywords: 'wom telefono celular' },
  ],
  gas: [
    { id: 'abastible', label: 'Abastible', path: '/chile-icons/gas/abastible.png', keywords: 'abastible gas' },
    { id: 'gasco', label: 'Gasco', path: '/chile-icons/gas/gasco.png', keywords: 'gasco gas' },
    { id: 'lipigas', label: 'Lipigas', path: '/chile-icons/gas/lipigas.png', keywords: 'lipigas gas' },
    { id: 'metrogas', label: 'Metrogas', path: '/chile-icons/gas/metrogas.png', keywords: 'metrogas gas' },
  ],
  agua: [
    { id: 'aguas_andinas', label: 'Aguas Andinas', path: '/chile-icons/agua/aguas_andinas.png', keywords: 'aguas andinas agua' },
    { id: 'aguas_nuevas', label: 'Aguas Nuevas', path: '/chile-icons/agua/aguas_nuevas.png', keywords: 'aguas nuevas agua' },
    { id: 'essbio', label: 'Essbio', path: '/chile-icons/agua/essbio.png', keywords: 'essbio agua' },
    { id: 'nuevosur', label: 'Nuevosur', path: '/chile-icons/agua/nuevosur.png', keywords: 'nuevosur agua' },
  ],
  tickets: [
    { id: 'amipass', label: 'Amipass', path: '/chile-icons/tickets/amipass.png', keywords: 'amipass ticket restaurant' },
    { id: 'cornershop', label: 'Cornershop', path: '/chile-icons/tickets/cornershop.png', keywords: 'cornershop delivery' },
    { id: 'edenred', label: 'Edenred', path: '/chile-icons/tickets/edenred.png', keywords: 'edenred ticket restaurant' },
    { id: 'glovo', label: 'Glovo', path: '/chile-icons/tickets/glovo.png', keywords: 'glovo delivery' },
    { id: 'pedidos_ya', label: 'PedidosYa', path: '/chile-icons/tickets/pedidos_ya.png', keywords: 'pedidos ya delivery' },
    { id: 'rappi', label: 'Rappi', path: '/chile-icons/tickets/rappi.png', keywords: 'rappi delivery' },
    { id: 'sodexo', label: 'Sodexo', path: '/chile-icons/tickets/sodexo.png', keywords: 'sodexo ticket restaurant' },
    { id: 'ticket_restaurant', label: 'Ticket Restaurant', path: '/chile-icons/tickets/ticket_restaurant.png', keywords: 'ticket restaurant' },
    { id: 'uber_eats', label: 'Uber Eats', path: '/chile-icons/tickets/uber_eats.png', keywords: 'uber eats delivery' },
  ],
  'medios-pago': [
    { id: 'fpay', label: 'Fpay', path: '/chile-icons/medios-pago/fpay.png', keywords: 'fpay pago' },
    { id: 'khipu', label: 'Khipu', path: '/chile-icons/medios-pago/khipu.png', keywords: 'khipu pago' },
    { id: 'mach', label: 'Mach', path: '/chile-icons/medios-pago/mach.png', keywords: 'mach pago banco' },
    { id: 'mercadopago', label: 'Mercado Pago', path: '/chile-icons/medios-pago/mercadopago.png', keywords: 'mercadopago mercado pago' },
    { id: 'multicaja', label: 'Multicaja', path: '/chile-icons/medios-pago/multicaja.png', keywords: 'multicaja pago' },
    { id: 'one_pay', label: 'OnePay', path: '/chile-icons/medios-pago/one_pay.png', keywords: 'onepay one pay pago' },
    { id: 'paypal', label: 'PayPal', path: '/chile-icons/medios-pago/paypal.png', keywords: 'paypal pago' },
    { id: 'redcompra', label: 'Redcompra', path: '/chile-icons/medios-pago/redcompra.png', keywords: 'redcompra pago' },
    { id: 'transbank', label: 'Transbank', path: '/chile-icons/medios-pago/transbank.png', keywords: 'transbank pago' },
    { id: 'webpay', label: 'Webpay', path: '/chile-icons/medios-pago/webpay.png', keywords: 'webpay pago' },
  ],
  tarjetas: [
    { id: 'american_express', label: 'American Express', path: '/chile-icons/tarjetas/american_express.png', keywords: 'american express tarjeta credito' },
    { id: 'dinners_club', label: "Dinner's Club", path: '/chile-icons/tarjetas/dinners_club.png', keywords: 'dinners club tarjeta credito' },
    { id: 'magna', label: 'Magna', path: '/chile-icons/tarjetas/magna.png', keywords: 'magna tarjeta credito' },
    { id: 'master_card', label: 'MasterCard', path: '/chile-icons/tarjetas/master_card.png', keywords: 'mastercard tarjeta credito' },
    { id: 'visa', label: 'Visa', path: '/chile-icons/tarjetas/visa.png', keywords: 'visa tarjeta credito' },
  ],
};

export const CHILE_CATEGORY_LABELS = {
  bancos: 'Bancos',
  isapres: 'Isapres',
  afp: 'AFP',
  telefonia: 'Telefonía',
  gas: 'Gas',
  agua: 'Agua',
  tickets: 'Tickets/Delivery',
  'medios-pago': 'Medios de Pago',
  tarjetas: 'Tarjetas',
};

export const getAhorroBankInfo = (bankName) => {
  if (!bankName) return null;
  const n = bankName.toLowerCase().trim();
  return BANCOS_CHILE.find(b => b.nombre.toLowerCase() === n) || null;
};
