ALTER TABLE users ADD COLUMN IF NOT EXISTS "nombre" TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "apellido" TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "email_verified" BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "verification_token" TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "google_id" TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "deleted_at" TIMESTAMPTZ DEFAULT NULL;
