export const TUTORIAL_CONFIG = {
  APP_NAME: 'Kuentas Klaras',
  APP_INITIAL: 'K',
  FORWARD_EMAIL: 'parse+ideusuario@adaptaweb.cl',

  COLORS: {
    primary: '#006c4d',
    mintDark: '#2dbc8b',
    mintBright: '#6de0b3',
    navyDeep: '#0a192f',
    secondary: '#515f78',
    surface: '#f7f9fb',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerHigh: '#e6e8ea',
    surfaceContainerHighEst: '#e0e3e5',
    surfaceContainerLow: '#f2f4f6',
    surfaceDim: '#d8dadc',
    onSurface: '#191c1e',
    onSurfaceVariant: '#3d4a43',
    outline: '#6d7a72',
    outlineVariant: '#bccac0',
    graySoft: '#f1f5f9',
    white: '#ffffff',
    error: '#ba1a1a',
    secondaryContainer: '#d2e0fe',
    onSecondaryContainer: '#55637d',
  },

  BANK_EMAILS: [
    'reply@info.bice.cl',
    'biceinforma@bancobice.cl',
    'bancobice@eeccvirtual.cl',
    'serviciodetransferencias@bancochile.cl',
    'enviodigital@bancochile.cl',
    'notificaciones@bancochile.cl',
    'enviodigital@bancoedwards.cl',
    'serviciotransferencias@bancochile.cl',
    'cartoladigital@bancofalabella.cl',
    'estadodecuenta@cmr.cl',
    'notificaciones@cl.bancofalabella.com',
    'mensajeria@santander.cl',
    'mensajes@santander.cl',
    'bdp@santander.cl',
    'contacto@bci.cl',
    'transferencias@bci.cl',
    'bcimail@bci.cl',
    'bci@eeccvirtual.cl',
    'notificaciones@bciplus.cl',
    'itau@eeccvirtual.cl',
    'transferencias@itau.cl',
    'itaupersonas@itau.cl',
    'cartola@itau.cl',
    'scotiabank@eeccdigital.cl',
    'avisos.info@scotiabank.cl',
    'cartolas.info@scotiabank.cl',
    'avisos.empresa.info@scotiabank.cl',
    'comprobantes.info@scotiabank.cl',
    'no-reply@tenpo.cl',
    'no-reply@tenpobank.cl',
    'inversiones@tenpo.cl',
    'no-reply@mail.machbank.cl',
    'contacto@mail.machbank.cl',
    'contacto@mail.somosmach.com',
    'noreply@somosmach.com',
    'estadodecuenta@correo.tarjetaliderbci.cl',
    'bancoestado@correo.bancoestado.cl',
    'bancoestado@eeccvirtual.cl',
    'notificaciones@correo.bancoestado.cl',
    'noreply@correo.bancoestado.cl',
    'info@mercadopago.com',
    'bancoconsorcio@bancoconsorcio.cl',
    'mensajes@bancoconsorcio.cl',
    'bancoripleyinforma@bancoripley.com',
    'informaciones@bancoripley.cl',
    'noresponder@bancosecurity.cl',
    'notificaciones@transaccionalcoopeuch.com',
    'mensajeria@copecpay.cl',
    'contacto@mail.global66.com',
    'no-reply@sender.global66.com',
    'mensajeria@heroesprepago.cl',
    'transferenciaprepago@losheroes.cl',
    'operaciones@infotapp.cl',
    'no.reply@losandesprepago.cl',
    'hola@fintual.com',
    'notificaciones@cencosudscotiabank.cl',
    'donotreply@metromuv.cl',
    'info@prexcard.cl',
    'bancointernacional@internacional.cl',
    'bancointernacional@eeccvirtual.cl',
    'no-reply@internacional.cl',
    'transferencias@transferencias.internacional.cl',
  ],

  STEPPER_LABELS: ['Inicio', 'Correo', 'Filtros', 'Final'],
  TOTAL_STEPS: 4,

  MESSAGES: {
    welcome: {
      title: 'Guía paso a paso donde te mostramos como crear una regla de reenvío de Emails bancarios hacia Kuentas Klaras.',
      subtitle: 'Solo correos bancarios',
      howItWorksTitle: '¿Cómo funciona?',
      securityTitle: 'Seguridad y privacidad primero',
      securityPoints: [
        'No requiere tus claves bancarias ni de email.',
        'Solo procesamos correos de transacciones oficiales.',
        'Puedes eliminar la regla cuando quieras.',
      ],
      ctaButton: 'Comenzar',
    },
    step1: {
      title: 'Agregar dirección a tu correo',
      instruction: 'Debes abrir tu E-mail en un computador',
      steps: [
        { num: 1, text: 'Clic en el icono de menú' },
        { num: 2, text: 'Clic en "Ver toda la configuración"' },
        { num: 3, text: 'Clic en pestaña "Reenvío y correo POP/IMAP"' },
        { num: 4, text: 'Clic en "Agregar una dirección de reenvío"' },
      ],
      copyButton: 'Copiar',
      copiedButton: '¡Copiado!',
      opcionalButton: '(Paso Opcional) Si Gmail solicita autorización',
    },
    opcional: {
      title: 'Verificación de Seguridad (Opcional)',
      subtitle: 'Solo si Gmail solicita confirmación adicional.',
      steps: [
        'Clic en "Siguiente" en la ventana de Google.',
        'En tu celular, presiona "Sí, soy yo".',
        'Selecciona el número que aparece en tu computador.',
        'Clic en "Continuar" y luego "Aceptar".',
        'Vuelve a "Reenvío y correo POP/IMAP" en Gmail.',
        'Verifica que la opción esté seleccionada y guarda.',
      ],
      nextButton: 'Listo, a la Parte 2',
    },
    step2: {
      title: 'PARTE 2: Filtro para emails bancarios',
      subtitle: 'Configuraremos Gmail para que envíe copias de seguridad de tus correos bancarios a Kuanto.',
      steps: [
        {
          num: 1,
          title: 'Copiar Direcciones',
          description: 'Copia la lista de direcciones de email bancarios.',
          buttonText: 'Copiar',
        },
        {
          num: 2,
          title: 'Configuración Gmail',
          description: 'Clic en ⚙️ > "Ver toda la configuración"',
        },
        {
          num: 3,
          title: 'Crear el Filtro',
          description: 'Pestaña "Filtros y direcciones bloqueadas" > "Crear un nuevo filtro"',
        },
      ],
      copiedButton: '¡Copiado al portapapeles!',
    },
    step3: {
      successTitle: '¡LISTA LA REGLA DE REENVÍO!',
      infoTitle: 'IMPORTANTE: Configuración de Notificaciones',
      infoDescription: 'Es esencial que actives las notificaciones por correo electrónico en cada uno de tus bancos para sincronizar en tiempo real.',
      closeButton: 'Cerrar',
    },
  },

  ANIMATIONS: {
    floatDuration: '6s',
  },
};

export const getBankEmailsString = () => TUTORIAL_CONFIG.BANK_EMAILS.join(' OR ');

export const COLORS = TUTORIAL_CONFIG.COLORS;
export const APP_NAME = TUTORIAL_CONFIG.APP_NAME;
export const FORWARD_EMAIL = TUTORIAL_CONFIG.FORWARD_EMAIL;
